# train/config_small.yaml
# Küçük veri seti için konfigürasyon (hızlı denemeler için)
path: C:/Users/Yusuf/Desktop/YL/Tez/dl-detection/train/dataset

train: train_small
val:   valid_small

# Sınıf sayısı ve isimleri
nc: 21
names:
  [
    "aeroplane", "bicycle", "bird", "boat", "bottle",
    "bus", "car", "cat", "chair", "cow",
    "diningtable", "dog", "horse", "motorbike", "person",
    "pottedplant", "sheep", "sofa", "train", "tvmonitor", "background"
  ]
